MODEL:
  TYPE: generalized_semseg
  CONV_BODY: ResNet.ResNet50_conv5_body
  FASTER_RCNN: False
  NUM_CLASSES: 19 
  
RESNETS:
    IMAGENET_PRETRAINED_WEIGHTS: 'lib/datasets/pretrain_model/resnext101_64x4d-e77a0586.pth'
SEM:
    USE_RESNET: False
    SEM_ON: True
    UNION: False
    DILATED: 8
    FC_DIM: 2048
    DIM: 256
    INPUT_SIZE: [640, 640]
    TRAINSET: 'train'
    ARCH_ENCODER: 'resnext101_dilated8_64'
    DECODER_TYPE: 'ppm_bilinear'
    DEEP_SUB_SCALE: [1.0, 0.4]
    DOWNSAMPLE: [2]
    OUTPUT_PREFIX: 'semseg_label'
DISP:
    DISP_ON: True
    DIM: 256
    USE_DEEPSUP: False
    OUTPUT_PREFIX: 'disp_label'
    DOWNSAMPLE: [3]

NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: False
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (1280,)
  MAX_SIZE: 1440
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 2
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ./output/DispSeg_X101d8_with_ppm_bilinear_1X
