MODEL:
  #TYPE: generalized_semseg
  TYPE: Generalized_SEMSEG
  CONV_BODY: ResNet.ResNet152_conv5_body
  FASTER_RCNN: False
  NUM_CLASSES: 19
RESNETS:
    IMAGENET_PRETRAINED_WEIGHTS: 'coco_predtrain/152_xt32.pkl'
    #IMAGENET_PRETRAINED_WEIGHTS: 'pretrained/R-101.pkl'
    RES5_DILATION: 4
    STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
    TRANS_FUNC: bottleneck_transformation
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
SEM:
    SEM_ON: True
    UNION: False
    FC_DIM: 2048
    DIM: 512
    INPUT_SIZE: [672, 672]
    TRAINSET: 'train'
    ARCH_ENCODER: 'ResnetX_dilated8'
    DECODER_TYPE: 'ppm_bilinear_deepsup'
    FREEZE_BN: True
    DEEP_SUB_SCALE: [1.0, 0.4]
    DOWNSAMPLE: [0, 3]
    OUTPUT_PREFIX: 'semseg_label'
    OHEM_ON: False
    OHEM_POS: 0.9
    #PSPNET_PRETRAINED_WEIGHTS: './cityscapes_final/pspnet50_model_30.pth'
DISP:
    DISP_ON: False
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  #TYPE: 'SGD'
  #LR_POLICY: 'ReduceLROnPlateau'
  TYPE: 'poly'
  LR_POLICY: 'Poly'
  #LR_POLICY: steps_with_decay
  BASE_LR: 0.0001
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: False
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (1024,1536,2048,3072,3584,4096)
  MAX_SIZE: 1440
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 2
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ./output/pspnet_resnext152_kaiming_coco_pretrain_0001
