MODEL:
  TYPE: Generalized_SEGDISP
  CONV_BODY: ResNet.ResNet50_conv5_body
  FASTER_RCNN: False
  NUM_CLASSES: 19 
GROUP_NORM:
    NUM_GROUPS: 64
RESNETS:
    IMAGENET_PRETRAINED_WEIGHTS: 'lib/datasets/pretrain_model/resnet50-imagenet.pth'
    USE_GN: False
SEM:
    LAYER_FIXED: False
    BN_LEARN: False
    USE_RESNET: False
    SEM_ON: True
    UNION: False
    DILATED: 8
    FC_DIM: 2048
    DIM: 256
    INPUT_SIZE: [512, 1024]
    TRAINSET: 'train'
    ARCH_ENCODER: 'resnet50_dilated8'
    DECODER_TYPE: 'ppm_bilinear_deepsup'
    DEEP_SUB_SCALE: [1.0, 0.4]
    DOWNSAMPLE: [0, 3]
    OUTPUT_PREFIX: 'semseg_label'
    USE_GE_BLOCK: False
    USE_AWM_BLOCK: False  
DISP:
    DISP_ON: True
    DIM: 256
    ORIGINAL: True
    USE_DEEPSUP: False
    USE_CRL_DISPRES: False
    USE_CRL_DISPFUL: False
    USE_MULTISCALELOSS: False
    OUTPUT_PREFIX: 'disp_label'
    DOWNSAMPLE: [3]

NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: False
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (1440,)
  MAX_SIZE: 1440
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 2
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ./output/DispSeg_R50d8_1X_DispFul_noDeep_wihtMultileLossAndSem_AWM
